# version: '3.8'

services:
  ai-assistant:
    env_file:
      - dev.env
    build: .
    devices:
      - "/dev/video0:/dev/video0"
    privileged: true
    container_name: ai-assistant
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - /dev/video0:/dev/video0
    # environment:
